version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
        - "actions/*"
    commit-message:
      prefix: "fix: "
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix: "
    groups:
      grafana:
        patterns:
          - "@grafana/*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix: "

  - package-ecosystem: "docker"
    directory: "/docker/otelcol"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix: "

  - package-ecosystem: "docker"
    directory: "/docker/k6"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix: "

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix: "
    ignore:
      - dependency-name: "symfony/*"
        update-types: ["version-update:semver-major"]
    groups:
      symfony:
        patterns:
        - "symfony/*"
        update-types:
        - "minor"
        - "patch"
      open-telemetry:
        patterns:
        - "open-telemetry/*"
        
