twig:
  default_path: '%kernel.project_dir%/templates'
  globals:
    appVersion: 0.37.1
    faroUrl: '%env(resolve:FARO_URL)%'
    faroNamespace: '%env(resolve:FARO_NAMESPACE)%'
  file_name_pattern: '*.twig'
when@test:
  twig:
    strict_variables: true
