workers:
  fixtures_load:
    cmd: ['bin/console', 'doctrine:fixtures:load', '--no-interaction']
  npm_encore_watch:
    cmd: ['npx', 'encore', 'dev', '--watch']
  messenger_consume_async: ~
  docker_compose: ~
