version: '3.8'

# Production environment override
services:
  php:
    image: ${IMAGES_PREFIX:-}app-php:${PROJECT_VERSION:-latest}-prod
    build:
      context: .
      target: php_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}
      FARO_URL: ${FARO_URL}

  caddy:
    image: ${IMAGES_PREFIX:-}app-caddy:${PROJECT_VERSION:-latest}-prod
    build:
      context: .
      target: caddy_prod
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
