---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "faro-shop.fullname" . }}-backend
  labels:
    {{- include "faro-shop.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: backend
    {{- include "faro-shop.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "faro-shop.fullname" . }}-backend
  labels:
    {{- include "faro-shop.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "faro-shop.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "faro-shop.labels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        app.kubernetes.io/component: backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "faro-shop.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Always
      containers:
        - name: caddy
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.caddy.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}-prod"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: shared-data
              mountPath: /var/run/php
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: SERVER_NAME
              value: "http://{{ include "faro-shop.fullname" . }}"
            - name: RABBITMQ_URL
              value: amqp://guest:guest@{{ .Release.Name}}-rabbitmq:5672/%2f/messages
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace={{ .Release.Namespace}},service.version={{ .Chart.AppVersion }},{{ .Values.app.otel.resource }}"
          {{ range $key, $value := .Values.caddy.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
        - name: php
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}-prod"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: shared-data
              mountPath: /var/run/php
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: DATABASE_URL
              value: "postgresql://app:!ChangeMe!@{{ .Release.Name }}-postgres:5432/app?serverVersion=15&charset=utf8"
            - name: MESSENGER_TRANSPORT_DSN
              value: amqp://guest:guest@{{ .Release.Name}}-rabbitmq:5672/%2f/messages
            - name: RABBITMQ_URL
              value: amqp://guest:guest@{{ .Release.Name}}-rabbitmq:5672/%2f/messages
            - name: FARO_NAMESPACE
              value: "{{ .Release.Namespace }}"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace={{ .Release.Namespace }},service.version={{ .Chart.AppVersion }},{{ .Values.app.otel.resource }}"
            {{ range $key, $value := .Values.app.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
      initContainers:
        - name: create-schema
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}-prod"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c", "php bin/console doctrine:migrations:migrate --no-interaction"]
          env:
            - name: DATABASE_URL
              value: "postgresql://app:!ChangeMe!@{{ .Release.Name }}-postgres:5432/app?serverVersion=15&charset=utf8"
            - name: RABBITMQ_URL
              value: amqp://guest:guest@{{ .Release.Name}}-rabbitmq:5672/%2f/messages
            {{ range $key, $value := .Values.app.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
        - name: load-fixtures
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}-prod"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c", "php bin/console doctrine:fixtures:load --no-interaction"]
          env:
            - name: DATABASE_URL
              value: "postgresql://app:!ChangeMe!@{{ .Release.Name }}-postgres:5432/app?serverVersion=15&charset=utf8"
            - name: RABBITMQ_URL
              value: amqp://guest:guest@{{ .Release.Name}}-rabbitmq:5672/%2f/messages
            {{ range $key, $value := .Values.app.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
      volumes:
        - name: shared-data
          emptyDir: { }
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
