apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    service: {{ .Release.Name }}-postgres
    {{- include "faro-shop.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: {{ .Release.Name }}-postgres
      port: 5432
      targetPort: 5432
  selector:
    service: {{ .Release.Name }}-postgres
