apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
      {{- include "faro-shop.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
