apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
      {{- include "faro-shop.labels" . | nindent 4 }}
data:
  POSTGRES_DB: ps_db
  POSTGRES_USER: ps_user
  POSTGRES_PASSWORD: SecurePassword
