name: Build PHP extensions
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - docker/php-ext/**
  push:
    branches:
      - main
    paths:
      - docker/php-ext/**
env:
  REGISTRY: ghcr.io
  IMAGES_PREFIX: ghcr.io/${{ github.repository }}-

jobs:
  lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
  build-extension-image:
    runs-on: ubuntu-latest
    needs:
      - lint
    permissions:
      contents: read
      packages: write
    steps:
      - name: Fetch source from event
        uses: actions/checkout@v3

      - run: cp env.template .env
        shell: bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: docker/php-ext
          platforms: linux/amd64,linux/arm64
          push: true
          target: ext-protobuf
          build-args: |
            --build-arg protobuf_version=3.24.4
          tags: |
            ghcr.io/${{ github.repository }}-app-php-ext:protobuf-3.24.4
          cache-from: type=gha
          cache-to: type=gha

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: docker/php-ext
          platforms: linux/amd64,linux/arm64
          push: true
          target: ext-grpc
          build-args: |
            --build-arg grpc_version=1.59.1
          tags: |
            ghcr.io/${{ github.repository }}-app-php-ext:grpc-1.59.1
          cache-from: type=gha
          cache-to: type=gha
