name: Build PHP base image
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/build-baseimage.yml
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/build-baseimage.yml
env:
  REGISTRY: ghcr.io
  IMAGES_PREFIX: ghcr.io/${{ github.repository }}-

jobs:
  lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
  build-base-image:
    runs-on: ubuntu-latest
    needs:
      - lint
    permissions:
      contents: read
      packages: write
    steps:
      - name: Fetch source from event
        uses: actions/checkout@v4

      - run: cp env.template .env
        shell: bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
          push: true
          pull: true
          target: php_base
          tags: |
            ghcr.io/${{ github.repository }}-php:8.3.1
          cache-from: type=gha
          cache-to: type=gha
